module Streamdeck.View exposing (root)

import Html             exposing (..)
import Html.Attributes  exposing (..)
import Streamdeck.Types exposing (..)

root : Maybe Streamdeck -> Html Msg
root list =
  case list of
    Just deck -> table [ class "deck" ]
                   [ tr []
                     [ td [ class "odd" ] []
                     , td [ class "even" ] []
                     , td [ class "odd" ] []
                     , td [ class "even" ] []
                     , td [ class "odd" ] []
                     ]
                   , tr []
                     [ td [ class "even" ] []
                     , td [ class "odd" ] []
                     , td [ class "even" ] []
                     , td [ class "odd" ] []
                     , td [ class "even" ] []
                     ]
                   , tr []
                     [ td [ class "odd" ] []
                     , td [ class "even" ] []
                     , td [ class "odd" ] []
                     , td [ class "even" ] []
                     , td [ class "odd" ] []
                     ]
                   ]
    Nothing -> table [ class "deck" ]
                 [ tr []
                   [ td [ class "odd" ] []
                   , td [ class "even" ] []
                   , td [ class "odd" ] []
                   , td [ class "even" ] []
                   , td [ class "odd" ] []
                   ]
                 , tr []
                   [ td [ class "even" ] []
                   , td [ class "odd" ] []
                   , td [ class "even" ] []
                   , td [ class "odd" ] []
                   , td [ class "even" ] []
                   ]
                 , tr []
                   [ td [ class "odd" ] []
                   , td [ class "even" ] []
                   , td [ class "odd" ] []
                   , td [ class "even" ] []
                   , td [ class "odd" ] []
                   ]
                 ]
